Вёрстка компонента histogram
js-tasks-ru/htmlcss-20240913_rensedlovskij911 pull request #4
Opened 2024-10-01 10:15 UTC by renat890

2024-10-01 10:16 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-02 09:51 UTC, GSemikozov requested changes

2024-10-02 09:51 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 100px;
50

2024-10-02 09:51 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
лишнее

2024-10-02 09:51 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  gap: 2px;
1

2024-10-02 09:51 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding: 12px 0 39px 0;
сверху - 8

2024-10-02 12:17 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-04 20:00 UTC, GSemikozov approved these changes

2024-10-04 20:00 UTC, merged